### PR TITLE
Added the power metrics table that takes data from telemetry and disp…

### PR DESCRIPTION
**Pull request by ShairYousuf**
…lays them.

I made the power metrics table. I also edited the styling for the navigation table. changes to the dashboard page component html and css were made to get both navigation and power metrics in a column. the styling of the min actual max component was changed, some css was deleted. I used the html and css of the natural gas component to position it on the display.

### CODE REVIEW

**Review by yeeteing — COMMENTED** [review]
look good to me, just need to add a screenshot of your work :)

**Comment by ShairYousuf** [comment]
screenshot:
image

**Comment by ShairYousuf** [comment]
screenshot2:
image

**Review by yeeteing — APPROVED** [review]
nice one, love it

**Pull request merged**
