### PR TITLE
generation of state-component

### PR DESCRIPTION
**Pull request by hhdtan**
generated state component

added state's selector to root html

created label and div elements in state's html

### CODE REVIEW

**Comment by yeeteing** [comment]
Hey, I think I did not explain the requirement properly. The task is to create an actual box with the design shown in the picture below, 
could you make the changes to look like that instead? Feel free to ask me any question if there are any confusion though!
Screen Shot 2021-01-31 at 4 21 27 PM

**Comment by hhdtan** [comment]
image

testing screenshot paste

**Comment by hhdtan** [comment]
image

**Comment by hhdtan** [comment]
note: the nav-bar is overflowing from its container, so there is an overlap between my box and the nav-bar - tested with f12, overflow:hidden for nav-bar

**Comment by hhdtan** [comment]
image
image

CSS updates, again.

**Review by yeeteing — APPROVED** [review]
made some changes in the state-component and logo-component. 
now it look like this
Screen Shot 2021-02-14 at 11 51 09 AM

**Pull request merged**
