### PR TITLE
Clean Up UI

### PR DESCRIPTION
**Pull request by yeeteing**
Screen Shot 2021-05-30 at 2 18 24 PM

### CODE REVIEW

**Comment by colton-smith** [comment]
Can we maybe get the indicator LEDS to be a sharper circle instead of fading to the background.

**Comment by Shamima-Ali** [comment]
The "Longitude" title in the Navigation-Info section of the page has a missing ":".

**Comment by yeeteing** [comment]
> The "Longitude" title in the Navigation-Info section of the page has a missing ":".

Great catch!

**Comment by yeeteing** [comment]
> I think the indicator LEDS should be a sharper circle instead of fading to the background.

ok, will make a change

**Comment by yeeteing** [comment]
Before (Heartbeat circle):
Screen Shot 2021-06-13 at 3 03 02 PM
After (Heartbeat circle):
Screen Shot 2021-06-13 at 3 03 47 PM

**Review by ShairYousuf — COMMENTED** [review]
Looks great.

**Comment by ShairYousuf** [comment]
image
image
The page looks like this on my screen, my screen is 1280 x 720
Maybe we could do something so that even if the ratio isn't ideal, the whole website loads as intended.

**Comment by yeeteing** [comment]
I think in the meantime, I will merge to the master first, and create a PR for that fix

**Pull request merged**
